#region Initializing any macros that are useful/related to obj_item_collection_screen
#endregion

#region Initializing enumerators that are useful/related to obj_item_collection_screen
#endregion

#region Initializing any globals that are useful/related to obj_item_collection_screen
#endregion

#region The main object code for obj_item_collection_screen

/// @param {Real} index		Unique value generated by GML during compilation that represents this struct asset.
function obj_item_collection_screen(_index) : par_menu(_index) constructor{
	// 
	info = "";
	
	/// @description 
	draw_gui = function(){
		var _cameraID = CAMERA.camera;
		var _width = camera_get_view_width(_cameraID);
		var _height = camera_get_view_height(_cameraID);
		draw_sprite_ext(spr_rectangle, 0, 0, 0, _width, _height, 0, HEX_BLACK, alpha * 0.5);
		
		var _screenCenterX = _width / 2;
		var _screenCenterY = _height / 2;
		shader_set_outline(font_gui_medium, RGB_DARK_GREEN);
		draw_menu_title(font_gui_medium, _screenCenterX, _screenCenterY - 10, fa_center, fa_middle, HEX_GREEN, RGB_DARK_GREEN, alpha);
		draw_item_info(font_gui_small, _screenCenterX, _screenCenterY + 10);
		shader_reset();
	}
	
	/// @description 
	/// @param {Asset.GMFont}	font
	/// @param {Real}			x
	/// @param {Real}			y
	draw_item_info = function(_font, _x, _y){
		outline_set_font(_font);
		draw_set_text_align(fa_center, fa_middle);
		draw_text_outline(_x, _y, info, HEX_WHITE, RGB_GRAY, alpha);
		draw_reset_text_align();
	}
	
	/// @description
	state_default = function(){
		if (keyboard_check_pressed(vk_z)){
			stateFlags |= (1 << DESTROYED);
		}
	}
	
	/// @description
	/// @param {String}	item		The name of the item that was collected.
	/// @param {String}	info		The text that explains what the collectible gives to Samus.
	/// @param {Real}	maxWidth	The maximum possible width that a single line of the info text can be.
	set_item_data = function(_item, _info, _maxWidth){
		title = _item;
		info = string_format_width(_info, _maxWidth, font_gui_small);
	}
}

#macro ITEM_SCREEN_DEFAULT		obj_item_collection_screen.state_default

#endregion

#region Global functions related to obj_item_collection_screen
#endregion