#region Initializing any macros that are useful/related to par_ui_element
#endregion

#region Initializing enumerators that are useful/related to par_ui_element
#endregion

#region Initializing any globals that are useful/related to par_ui_element
#endregion

#region The main object code for par_ui_element

/// @param {Real} index		Unique value generated by GML during compilation that represents this struct asset.
function par_ui_element(_index) : base_struct(_index) constructor{
	x = 0;
	y = 0;
	
	alpha = 0;
	alphaTarget = 0;
	alphaModifier = 0;
	
	// 
	end_step = function() {}
	draw_gui = function(_alpha) {}
}

#endregion

#region Global functions related to par_ui_element
#endregion