#region Initializing any macros that are useful/related to obj_main_menu
#endregion

#region Initializing enumerators that are useful/related to obj_main_menu
#endregion

#region Initializing any globals that are useful/related to obj_main_menu
#endregion

#region The main object code for obj_main_menu

/// @param {Real} index		Unique value generated by GML during compilation that represents this struct asset.
function obj_main_menu(_index) : par_menu(_index) constructor{
	
}

#endregion

#region Global functions related to obj_main_menu
#endregion