// Prevent the object from processing anything if it has been destroyed OR it is currently inactive.
if (ENTT_IS_DESTROYED || !ENTT_IS_ACTIVE) 
	return;

// Overwrite the current state the value contained in the "nextState" variable only if the value contained
// within said variable is a valid index for a script/method value generated by Game Maker.
if (curState != nextState) {curState = nextState;}

// Call the general entity function for the "End Step" event that updates the positions of each active component
// currently attached to the entity relative to its position and any offsets that may exist.
entity_end_step();